on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Apache Maven Central
        run: ./gradlew publish
        env:
          OSSHR_USERNAME: ${{ secrets.OSSHR_USERNAME }}
          OSSHR_TOKEN: ${{ secrets.OSSHR_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}