on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          server-id: osshr
          server-username: OSSHR_USERNAME
          server-password: OSSHR_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Debug Info
        run: cat /home/runner/.m2/settings.xml

      - name: Publish to Apache Maven Central
        run: mvn deploy
        env:
          OSSHR_USERNAME: ${{ secrets.OSSHR_USERNAME }}
          OSSHR_TOKEN: ${{ secrets.OSSHR_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}